<template>
  <div class="loading-screen">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;"
      width="200px"
      height="200px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <circle
        cx="50"
        cy="50"
        fill="none"
        stroke="#e91e63"
        stroke-width="3"
        r="16"
        stroke-dasharray="75.39822368615503 27.132741228718345"
        transform="rotate(83.5254 50 50)"
      >
        <animateTransform
          attributeName="transform"
          type="rotate"
          repeatCount="indefinite"
          dur="1s"
          values="0 50 50;360 50 50"
          keyTimes="0;1"
        ></animateTransform>
      </circle>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
    <p>Loading...</p>
  </div>
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'

@Component
export default class BaseLoadingScreen extends Vue {}
</script>

<style scoped lang="scss">
@import '~/theme/colors';

.loading-screen {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  color: $color-dark-gray;
  font-size: 16px;
  height: 100%;
}
</style>
